branches:
  only:
    - master
    - /^v\d+.\d+(.\d+)?(-\S*)?$/
    - /^feat\/.*$

environment:
  matrix:
    - PYTHON: "C:\\Python36"

    - PYTHON: "C:\\Python37"

    - PYTHON: "C:\\Python38"

install:
  - "%PYTHON%/python.exe -m pip install -U pip"
  - "%PYTHON%/python.exe -m pip install -U pipenv"

build: false

test_script:
  - "%PYTHON%/Scripts/pipenv install --dev"
  - "%PYTHON%/Scripts/pipenv run pytest tests"

skip_tags: true

notifications:
  - provider: Webhook
    url:
      secure: Td6i7vvha+1BdTEBf6UyXHyBGwRw29cnlS6KHL4M59QbVzJWBuV+Gyr1ypH6jnBFMNPHqLz+tVYmeGeFhAOPRA==
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
